### ISSUE TITLE
small issue about how laravel-whoops handles NotFoundHttpException

### ISSUE THREAD

**Issue by marco-solare** [guidovanbiemen/laravel-whoops#1]
Hi Guido, 
your little package is great, I started using it in my latest l5 app, however I may have spotted some 
behaviour which might not be desired (well at least in my case):

* I created a new l5 app through the laravel command
* I pulled laravel-whoops in through composer
* I added 'Gvb\Whoops\ServiceProvider', to app.php
* it works ( great :)
* I define a 404 file: resources/views/errors/404.blade.php
* I go to some url like laravel5.dev/nonexistingurl
* I see laravel-whoops output:
Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException
(in the "code" box I see:)  throw new NotFoundHttpException; 

so this Exception is being handled by laravel-whoops, however in my opinion it should not but instead the 404 view should be rendered if a 404 error page exists.
Strangely I added  ` 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' `  to
    `protected $dontReport = [ 'Symfony\Component\HttpKernel\Exception\HttpException' `

but that did not result in any effect.

I then discovered in mattstaufer's blog:
http://mattstauffer.co/blog/bringing-whoops-back-to-laravel-5

That he added this little thing to his `render()` method:
 	`if ($this->isHttpException($e))`
        `{      return $this->renderHttpException($e);   }`

Now, when I add this to **your** `render()` method before the line `if (config('app.debug'))` then I will get the 404 page.

If I configure `app.debug` to `false` and your package is enabled in `config/app.php` I still don't get the 404 page.

It shows up immediately when I disable your package.

So if I'd use your package like it is right now I would have to have different `app.php` files for dev and production - which would be mad.

What do you think, could you review my problem and "solution" for this and maybe put it into your package?

I was using `laravel/framework (v5.0.0)` and updated to `laravel/framework (v5.0.2)` today - the behaviour existed in both versions.

best,
Marco.

**Comment by guidovanbiemen** [comment]
Thanks for the detailed report, I'll look into it.

**Comment by marco-solare** [comment]
cool, looking forward to your findindgs!
